#!/sbin/sh

#
# Unlock vendor partition
#

VENDOR=/dev/block/bootdevice/by-name/vendor
BLOCKDEV=/dev/block/sdf

safeRunCommand() {
   cmnd="$@"
   $cmnd
   ERROR_CODE=$?
   if [ ${ERROR_CODE} != 0 ]; then
      printf "Error while executing command: '${command}'\n"
      exit ${ERROR_CODE}
   fi
}

if [ ! -e "$VENDOR" ]; then
    echo "Creating vendor partition."

    # Change partition typecode to '8300 Linux filesystem'
    command="/sbin/sgdisk --typecode=5:8300 $BLOCKDEV"
    safeRunCommand $command

    # Change partition name to 'vendor'
    command="/sbin/sgdisk --change-name=5:vendor $BLOCKDEV"
    safeRunCommand $command

    echo "!!!Format vendor AFTER you reboot into TWRP!!!"
else
    echo "Vendor partition already exists!"
fi

exit 0
